### ISSUE TITLE
Background pic is replaced by plain blue on logon

### ISSUE THREAD

**Issue by benoithamet** [Microsoft/adfsWebCustomization#12]
Hi there

the background pic (first screenshot) is replace by plain blue color when getting the logon (second screenshot)

![background](https://user-images.githubusercontent.com/15656722/33789316-d024b2e4-dccb-11e7-9a58-4440ab1255a7.png)

![plainblue](https://user-images.githubusercontent.com/15656722/33789323-d612bd5e-dccb-11e7-8b3b-e61038e79f3c.png)

**Comment by bongiovimatthew-microsoft** [comment]
Thanks for the feedback! 

This is likely due to the JavaScript not being updated to point to your illustration. The documentation doesn't do a good job of explaining that you need to do this, so I'll take a bug fix on the docs.

What you'll want is to look at the last few lines of the paginatedOnload.js. You'll need to uncomment the last line, and point it to your illustration image location.

**Comment by benoithamet** [comment]
Thanks
did it but still no luck; even re ran the command to include the custom js file after the update

**Comment by bongiovimatthew-microsoft** [comment]
Interesting. Would you mind sending the full page source for both the working and non-working scenarios?

**Comment by dannyv72** [comment]
It's related to IE not knowing startwith.
If you add following code to the top of the js file, it works.  Verified in IE and Chrome.

if (!String.prototype.startsWith) {
    String.prototype.startsWith = function(searchString, position){
      position = position || 0;
      return this.substr(position, searchString.length) === searchString;
  };
}

**Comment by bongiovimatthew-microsoft** [comment]
Thanks @dannyv72 for the fix. We have pulled the change into the master branch. @benoithamet, does this fix the issue you were seeing?

**Comment by benoithamet** [comment]
Thanks Danny
Tried but still not getting the background pic; still the plain blue

**Comment by bongiovimatthew-microsoft** [comment]
Thanks benoithamet, a few more things to try. 
Our previous startsWith function declaration wasn't in the correct place. If you try from this branch, it should be in the correct spot: https://github.com/Microsoft/adfsWebCustomization/tree/addStartsWith/centeredUi 

Also, if you are still seeing issues, could you try using a PNG image instead of a JPG image (if your image is in fact a JPG).

**Comment by benoithamet** [comment]
Hi Matt
all good then :)

thanks
